runtime: ruby266

entrypoint: bundle exec puma -C ./puma.rb

instance_class: F2

env_variables:
  APP_ENV: staging
  THREAD_COUNT: 16

handlers:
- url: /images
  static_dir: public/images
  secure: always

- url: /.*
  script: auto
  secure: always